### PR TITLE
Max assertion age configurable

### PR DESCRIPTION
**Pull request by tmulkern**
I added the code necessary to allow the Max Assertion Age to be changed.

### CODE REVIEW

**Comment by tmulkern** [comment]
@rkarodia bump

**Comment by rkarodia** [comment]
Changes look good, just waiting for the change in the common project so that I can version it and update the pom file

**Comment by tmulkern** [comment]
@rkarodia thanks

**Comment by tmulkern** [comment]
@rkarodia any idea when this could be released into the atlassian mark place?

**Pull request merged**
